# Generated by Django 3.0.6 on 2020-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist_search',
            options={'verbose_name': 'Playlist search', 'verbose_name_plural': 'Playlist searches'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search environment', 'verbose_name_plural': 'Search environments'},
        ),
        migrations.AlterModelOptions(
            name='track_search',
            options={'verbose_name': 'Track search', 'verbose_name_plural': 'Track searches'},
        ),
        migrations.AddField(
            model_name='playlist_search',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track_search',
            name='name',
            field=models.CharField(default='default trackname', max_length=200),
            preserve_default=False,
        ),
    ]
